# Generated by Django 3.2 on 2021-12-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_reservedinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedinfo',
            name='status',
        ),
    ]
